[DESK-704]filter and sort
remoteit/desktop pull request #261
Opened 2020-10-01 01:54 UTC by mauricio0000

### Description

Add feature sort and filter

### Checklist

- [ ] Pull Request title is in the format `[PROJ-12345] Some useful description here...`
- [ ] I have prefixed this PR with `[WIP]` if it is a Work In Progress (not ready to merge)
- [ ] The git branch is in the format `PROJ-12345-some-useful-description-here`
- [ ] I have added one or more reviewers
- [ ] I have added/updated tests for any code changes
- [ ] I have updated documentation (including README, inline comments and docs.remote.it docs)
- [ ] This PR only contains one isolated change (bug fix, feature, etc)
- [ ] Translation strings added/updated for all user-visible text
- [ ] I have manually reviewed this PR to make sure only the files I intended to change were changed and nothing else
- [ ] I have notified reviewers on Slack by @ mentioning them in the `#desktop`channel
- [ ] I have moved the Jira ticket into `Resolved` state and made a note in the ticket with a link to this PR

### Test plan

1. Sign in
2. Go to devices
3. You should see the new section of filters and sort

### Ticket

https://remoteit.atlassian.net/browse/DESK-756

2020-10-01 01:54 UTC, mauricio0000 commented
Miss sort by color and owner, waiting for changes API

2020-10-04 16:39 UTC, JamieRuderman requested changes
Looks really good overall. Love the feature. Main thing is just to replace the <Divider /> component with I'm thinking the <Collapse /> component. Then the css should all fall into place.
Thanks!

2020-10-04 16:39 UTC, JamieRuderman commented on frontend/src/components/DeviceList/DeviceList.tsx
> +          [css.contentShift]: open,
We need to replace the <Drawer> MuiComponent with probably a <Collapse> one. Then if in a Flexbox it should all just naturally move over.

2020-10-04 16:39 UTC, JamieRuderman commented on frontend/src/components/FilterDrawerContent/FilterDrawerContent.tsx
> +    <Drawer
Let's change this to a <Collapse> and see if we can remove all the extra code trying to make the Drawer work inside a container.

2020-10-04 16:39 UTC, JamieRuderman commented on frontend/src/pages/DevicesPage/DevicesPage.tsx
> +  const handleDrawer = (state: boolean) => {
```suggestion
  const onOpen = (state: boolean) => {
```

2020-10-04 16:39 UTC, JamieRuderman commented on frontend/src/pages/DevicesPage/DevicesPage.tsx
> +        <DeviceList devices={devices} connections={connections} handleDrawer={handleDrawer} open={open} />
```suggestion
        <DeviceList devices={devices} connections={connections} onOpen={onOpen} open={open} />
```

2020-10-04 16:39 UTC, JamieRuderman commented on frontend/src/pages/DevicesPage/DevicesPage.tsx
> +            <FilterButton handleDrawer={handleDrawer} open={open} />
Could also be called onOpenDrawer....
```suggestion
            <FilterButton onOpen={onOpen} open={open} />
```

2020-10-04 16:39 UTC, JamieRuderman commented on frontend/src/components/FilterDrawerContent/index.ts
> +export { FilterDrawerContent } from './FilterDrawerContent'
I've started just making components not wrapped in folders. Feel free to do the same if so inclined.   🙂

2020-10-04 16:39 UTC, JamieRuderman commented on frontend/src/components/FilterDrawerContent/FilterSelector.tsx
> +  }
```suggestion
  function TheFilter(props: { value: string; filterName: string }) {
    const selected = props.value === owner || props.value === filter || props.value === sort
      return (
        <Typography color={selected ? 'primary' : undefined}>
          <ListItemText className={css.name} primary={props.filterName} />
        </Typography>
      )
  }
```

2020-10-19 19:18 UTC, JamieRuderman requested changes
Just looks like a merge issue in the DeviceList.tsx, otherwise all looks awesome!
I marked WIP until we are ready to merge.

2020-10-19 19:18 UTC, JamieRuderman commented on frontend/src/components/DeviceList/DeviceList.tsx
>                </ListItem>
```suggestion
```

2020-10-19 19:18 UTC, JamieRuderman commented on frontend/src/components/DeviceList/DeviceList.tsx
> +                  <Notice>This device is registered to another user</Notice>
```suggestion
                  <Notice>This device is not registered to you.</Notice>
```

2020-10-19 19:18 UTC, JamieRuderman commented on frontend/src/components/DeviceList/DeviceList.tsx
> +            devices.map(
```suggestion
        {devices.map(	
```

2020-10-19 19:18 UTC, JamieRuderman commented on frontend/src/components/DeviceList/DeviceList.tsx
> +            </Body>
```suggestion
```

Check these edits, I think they are probably pulled from an older version of the file and aren't right.

2020-11-03 19:06 UTC, JamieRuderman approved these changes
Looks great thanks!

2020-11-03 19:06 UTC, merged