[DESK-803] icons remoteit components
remoteit/desktop pull request #312
Opened 2020-11-25 22:55 UTC by mauricio0000

### Description
 icons remoteit components

### Checklist

![image](https://user-images.githubusercontent.com/65682530/100289635-1de35f80-2f58-11eb-94d0-10b0e10313ca.png)

### Test plan

 icons slow to load in Admin Panel

### Ticket

https://remoteit.atlassian.net/browse/DESK-803

2020-12-07 20:05 UTC, JamieRuderman requested changes
Looks good, I just don't think we want the changes in these files:
- SearchField.tsx 
- RefreshButton.tsx 
- DeviceSetupItem.tsx 

Also you should see if we can remove the font files.

2020-12-07 21:01 UTC, mauricio0000 commented
@JamieRuderman 

Font files were deleted 

https://github.com/remoteit/desktop/blob/f854eeba586bdd0655e090ede8a81fb788c15871/frontend/src/components/Icon/vendor/all.min.css

https://github.com/remoteit/desktop/blob/f854eeba586bdd0655e090ede8a81fb788c15871/frontend/src/components/Icon/Icon.css

2020-12-17 07:13 UTC, JamieRuderman requested changes
Please see comments thanks!

2020-12-17 07:13 UTC, JamieRuderman commented on frontend/src/components/Icon/Icon.tsx
> +      break
We also need to support the `regular` and `solid` weights.

2021-01-07 00:48 UTC, JamieRuderman approved these changes
Thanks!

2021-01-07 00:48 UTC, merged