[DESK-926] bind ip edit and validation
remoteit/desktop pull request #426
Opened 2021-03-08 13:40 UTC by mauricio0000

### Description

bind ip edit and validation

### Test plan
https://remoteit.atlassian.net/wiki/x/AYBHO

https://remoteit.atlassian.net/browse/DESK-926

2021-03-09 20:59 UTC, JamieRuderman requested changes
I checked out the branch, but couldn't get to the page, so made some fixes and committed them.  Please pull. Also the Save button doesn't enable so you can't save, except if you change the bind IP address - then if you have an error it shows the error and then saves anyway. Also I don't think we need the IP address validation because I think you might want to enter in a dns name like "localhost" or "system.local"

2021-03-18 19:33 UTC, JamieRuderman requested changes
I tested and when I turned it on and clicked save it didn't turn on and save.

2021-03-22 20:27 UTC, mauricio0000 commented on backend/src/sharedCopy/constants.ts
> -export const REGEX_VALID_HOSTNAME = /^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9]):[0-9]+$/
this REGEX was checking port

2021-03-24 21:56 UTC, JamieRuderman requested changes

2021-03-24 21:56 UTC, JamieRuderman commented on frontend/src/pages/LanSharePage/LanSharePage.tsx
> +  const [bindIP, setBindIP] = useState(IP_OPEN)
```suggestion
```
I don't think you want a new state for `bindIP`. `bindIP` is the same as `currentHost` I think.

2021-03-26 22:41 UTC, JamieRuderman approved these changes

2021-03-26 23:13 UTC, merged