[DESK-1142] SSH launch
remoteit/desktop pull request #512
Opened 2021-07-12 22:35 UTC by mauricio0000

### Description

[DESK-1142] SSH launch

### Ticket

https://remoteit.atlassian.net/browse/DESK-1142

2021-07-12 22:53 UTC, JamieRuderman requested changes
I saw this dialog on my mac:
<img width="1392" alt="Screen Shot 2021-07-12 at 3 50 21 PM" src="https://user-images.githubusercontent.com/864957/125365384-01e6cf80-e329-11eb-87f8-947bfb79456d.png">

It should only appear on windows when putty isn't available.
Also it should remember the state the user chooses in memory so they only have to do it once every time they start the app.

2021-07-22 16:28 UTC, JamieRuderman requested changes
When I tried launching an ssh connection with a missing token [username] it did not prompt me for the username.

2021-07-23 16:32 UTC, JamieRuderman requested changes
@mauricio0000 Mac testing was good. But didn't pass my Windows testing. Got stuck on this screen:

<img width="2032" alt="Screen Shot 2021-07-23 at 9 30 52 AM" src="https://user-images.githubusercontent.com/864957/126813281-86fce7f6-2888-41c7-a3a3-f585a6b669a5.png">

2021-08-03 18:41 UTC, JamieRuderman requested changes
Let's re-review - still having issues launching in Windows:

Error:
<img width="2032" alt="Screen Shot 2021-08-03 at 11 34 46 AM" src="https://user-images.githubusercontent.com/864957/128068646-998654f8-fe61-4ac1-a326-fde2140cedfe.png">

And showing Putty when launching RDP:
<img width="2032" alt="Screen Shot 2021-08-03 at 11 36 10 AM" src="https://user-images.githubusercontent.com/864957/128068692-1c7ece8c-23a9-4710-a0d2-f77ab82a054a.png">

I think we should fix this the right way and integrate with the `frontend/src/shared/applications.ts` class. Let's discuss. 

Thanks!

2021-10-06 15:21 UTC, mauricio0000 commented on backend/src/sharedCopy/applications.ts
> +  checkApplicationCmd: string = ''
by default it is empty

2021-10-06 15:25 UTC, javierdac requested changes

2021-10-06 15:25 UTC, javierdac commented on frontend/src/buttons/LaunchButton/LaunchButton.tsx
> +  }, [loading])
Is it not necessary to add openLaunchApplication in here?

2021-10-06 15:25 UTC, javierdac commented on frontend/src/components/DialogApp/DialogApp.tsx
> +          <Button onClick={getApp} style={{ borderRadius: 3, left: '-120px' }} variant="contained" color="primary"   >{buttonText}</Button>
we should add a stylesheet on this

2021-10-06 15:25 UTC, javierdac commented on frontend/src/services/Browser.ts
> +  if (launchPutty(typeID)) {
should not be better to use switch in here?

2021-10-06 16:22 UTC, merged