[DESK-1135] send feedback
remoteit/desktop pull request #513
Opened 2021-07-13 16:36 UTC by mauricio0000

### Description

send feedback UI

### Test plan

1. Sign in
2. Go to lateral menu
3. Click on `Send Feedback`
4. You should see a modal for feedback

### Ticket
https://remoteit.atlassian.net/browse/DESK-1135

2021-07-13 17:30 UTC, mauricio0000 commented
<img width="1295" alt="Screen Shot 2021-07-13 at 13 34 21" src="https://user-images.githubusercontent.com/65682530/125498603-7c7436d1-33a0-4189-a099-22b5eafcea82.png">

2021-07-20 21:18 UTC, JamieRuderman requested changes

2021-07-20 21:18 UTC, JamieRuderman commented on frontend/src/models/feedback.ts
> +        // if (!errors) {
Form should submit to ZenDesk API. Please see ticket description.
https://developer.zendesk.com/api-reference/
Thank you!

2021-07-30 20:55 UTC, JamieRuderman requested changes
Looks good! It just needs a system message saying "Thank you. Feedback sent!" after sending...
https://remoteit.atlassian.net/browse/DESK-1135

2021-08-03 17:43 UTC, JamieRuderman approved these changes
Thanks!

2021-08-03 18:41 UTC, merged