[DESK-1265] help messagge
remoteit/desktop pull request #586
Opened 2021-11-24 20:17 UTC by mauricio0000

### Description
[DESK-1265] help messagge

### Test plan

### Ticket
https://remoteit.atlassian.net/browse/DESK-1265

2021-11-25 12:11 UTC, javierdac requested changes

2021-11-25 12:11 UTC, javierdac commented on frontend/src/components/SharingForm/SharingForm.tsx
> +  const disabled = !users?.length && email === '' ? true : false
you can take out the condition ? true : false

2021-11-25 14:18 UTC, javierdac approved these changes

2021-12-02 18:24 UTC, JamieRuderman approved these changes

2021-12-02 18:24 UTC, merged